<?php
$cols = array(
    "browserid", "parent", "browser_bits", "platform",
    "platform_description",
    "platform_bits",
    "platform_maker",
    "javaapplets",
    "device_name",
    "device_maker",
    "device_code_name",
    "device_brand_name",
    "renderingengine_name",
    "renderingengine_version",
    "renderingengine_description",
    "renderingengine_maker",
    "comments",
    "browser",
    "browser_type",
    "browser_maker",
    "version",
    "majorver",
    "frames",
    "iframes",
    "tables",
    "cookies",
    "javascript",
    "ismobiledevice",
    "cssversion",
    "device_type",
    "device_pointing_method",
    "browser_modus",
    "minorver",
    "platform_version",
    "alpha",
    "beta",
    "win16",
    "win32",
    "win64",
    "backgroundsounds",
    "vbscript",
    "activexcontrols",
    "istablet",
    "issyndicationreader",
    "crawler",
    "isfake",
    "isanonymized",
    "ismodified",
    "privacy_score",
    "new_privacy_score"
);
$types = array(
    "i", "v", "i", "v", "v", "i", "v", "f", "v", "v", "v", "v",
    "v", "v", "v", "v", "v", "v", "v", "v", "v", "v", "f", "f", "f", "f", "f", "f",
    "i", "v", "v", "v", "v", "v", "f", "f", "f", "f", "f", "f", "f", "f", "f", "f", "f", "f",
    "f", "f", "i", "f"
);
